-- Seed demo accounts + a sample invoice record.
-- Passwords are PBKDF2 hashes (generated by gen-seed.js): Admin@123 / Demo@123
-- NOTE: run schema.sql first, then this file.

INSERT OR IGNORE INTO users (name,email,password_hash,is_admin,plan,plan_status,plan_renews)
VALUES
 ('Site Admin','admin@demo.com','__ADMIN_HASH__',1,'Enterprise','Active',date('now','+24 day')),
 ('Demo User','demo@demo.com','__DEMO_HASH__',0,'Pro','Active',date('now','+24 day'));

INSERT INTO activity (user_id,type,detail,ip)
SELECT id,'account_created','Account registered','203.0.113.10' FROM users WHERE email='demo@demo.com';
INSERT INTO activity (user_id,type,detail,ip)
SELECT id,'login','Signed in with password','203.0.113.10' FROM users WHERE email='demo@demo.com';
INSERT INTO activity (user_id,type,detail,ip)
SELECT id,'subscription','Upgraded to Pro plan','203.0.113.10' FROM users WHERE email='demo@demo.com';
